### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES] on devices with Adroid < 7.0

### ISSUE THREAD

**Issue by siriuzwhite** [werty1st/KinoCast#3]
Your provided APK can't be installed on devices < Android 7.0 because of a certificate error.
Possible fix: https://stackoverflow.com/a/43097991

**Comment by QDaniel** [comment]
a new Version is released: https://github.com/werty1st/KinoCast/releases/tag/1.6.7
