### ISSUE TITLE
Streamcherry, Streamango, Vidoza, Vshare not working

### ISSUE THREAD

**Issue by siriuzwhite** [werty1st/KinoCast#4]
Error: "Fehler beim Auflösen des Hosts! Die Datei wurde möglicherweiße gelöscht."
But the tested streams are up in a normal browser.

**Comment by QDaniel** [comment]
Closed by 53c3fe81147f4358c34cbf3f913b193309a24f1c

**Comment by QDaniel** [comment]
Fixed by https://github.com/werty1st/KinoCast/releases/tag/1.6.9
