### ISSUE TITLE
Integrated updater broken

### ISSUE THREAD

**Issue by siriuzwhite** [werty1st/KinoCast#5]
Update dialog pops up on app start but after the download progressbar is at 100% the app crashes/closes without initiating the update.

**Comment by QDaniel** [comment]
Closed with Version 1.7.1

**Comment by siriuzwhite** [comment]
Still not working for me. After downloading the APK it just says "File Downloaded" in the app, but doesn't initiate the update. (Android 5.1.1)

P.S. Dont know if intentended or not, but I cant open issues in your @QDaniel repository: https://github.com/QDaniel/KinoCast

**Comment by QDaniel** [comment]
Wich  version is installed? Before 1.7.1 you must update manually.

https://github.com/QDaniel/KinoCast/releases/download/1.7.1/com.ov3rk1ll.kinocast_v1.7.1.Optimus.Prime.apk

**Comment by siriuzwhite** [comment]
I've tested it with 1.7.4

**Comment by siriuzwhite** [comment]
I've tested with your latest commit (after setting version number back to 18198)
Now after the download the application chooser pops up and says "No application can perform this action"

**Comment by QDaniel** [comment]
Can you test the last commit?

**Comment by siriuzwhite** [comment]
Nice, now it works: installer opens after download.
